import { ApiProperty } from "@nestjs/swagger";

export class ShortenResponseDto {
    @ApiProperty({description: "The url generated by the shortening process", example: "http://localhost:8081/sdafsd1d"})
    public newUrl: string;
    constructor(newUrl: string) {
        this.newUrl = newUrl;
    }
}
